- name: Download jboss
  get_url:
    url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip
    dest: /opt

- name: unzip jboss
  unarchive:
    src: /opt/jboss-as-7.1.1.Final.zip
    dest: /opt
    remote_src: yes
